#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N stats
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

mkdir stats
mkdir localR

#module load r/3.5.1-py2.7
module load R-3.4.1

cd "/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/VCFS/"

#fgz1=$1
#fgz=`basename $fgz1`

## f is the file
#gunzip -f $fgz
#f=${fgz%.gz}
##f=$1

echo "R_LIBS_USER=$PWD/localR/" > .Renviron

Rscript --no-save /home/kprovost/nas3/5.testingPopgenome_emperical.R



