#!/bin/bash

echo $M $Nf $m $O $r $i $v $B >> progress.txt 2>&1

## slim-grow-neut-nospat-1pop-isol.job
bash 1.run_slim_2pop_recpacitate.sh \
-a 0 -B "$B" -c 1 \
-e "vireotest_slim_TRANSITION_57x87_coarse.txt" \
-f "$Nf" -g 1.00 -G 2000 \
-h "n" -H 2000 \
-I "0.twopopulations_variable_parameters.slim" \
-i "$i" -l 1 -m "$m" \
-M "$M" -N "$Nf" \
-o "migrate-$M-popsize-$Nf-mut-$m-gen-$O-recom-$r-ibd-$i-seccon-$v-pop-$B" \
-O "$O" \
-P "" \
-p slim \
-r "$r" -s 20 \
-S 2 -t 1 -v "$v" \
-V 1000 -w "0.0" -X 0.02 \
-x 57 -y 87 
>> "slimlog-migrate-$M-popsize-$Nf-mut-$m-gen-$O-recom-$r-ibd-$i-seccon-$v-pop-$B.log" 2>&1

# -a flag # use all pops or not 		# default 0
# -B flag # number of subpops 			# default 1
# -c flag # competition yes/no			# default 1 -- only works if spatial 1
# -e flag # ENM filename 				# default /Users/kprovost/Documents/Classes/Machine_Learning/SLiMTreeSeqPub-master/vireotest_slim_27x45.asc
# -f flag # ending pop size 			# default same as $N
# -G flag # growth generation start		# default 1000
# -g flag # growth/contract rate 		# default 1 (no growth or contract), under 1 shrinks, over 1 grows
# -H flag # sweep generation start		# default 1000
# -h flag # what type of sweep wanted 	# default "n" no sweep, "h" hard sweep, "s" soft sweep ## consider adding things for balancing, etc
# -i flag # ibd yes/no					# default 1 -- only works if spatial 1
# -I flag # which slim file 			# default "model.slim"
# -l flag # spatial yes/no 				# default 0
# -M flag # migration rate 				# default 0
# -m flag # mutation rate 				# default 1e-7
# -N flag # beginning pop size 			# default 1000
# -o flag # name of output file 		# default "modeltest"
# -O flag # output generation 			# default 2000
# -P flag # path 						# default 1
# -p flag # where slim is located 		# default "slim"
# -r flag # recombination rate 			# default 1e-8
# -s flag # number genomes to output 	# default 20
# -S flag # number of reps to run 		# default 2
# -t flag # use treeseq or not 			# default 1
# -v flag # secondary contact or not 	# default 0
# -V flag # seccon gen before finish	# default 100
# -w flag # selection coefficient		# default 0.5 (beneficial), 0 neutral, negative deleterious
# -x flag # niche model X dimension		# default 27
# -X flag # scaling factor				# default 1
# -y flag # niche model Y dimension		# default 45

gzip -f *tree*
gzip -f *log*