#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N popgenome
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

date
time

cd /home/kprovost/nas3/

# for i in /vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/MSFILES/*/*/; 
# do echo $i; 
# qsub -v path=$i /home/kprovost/nas3/popgenome_job.job; 
# done;

module load R-3.4.1

echo $path

Rscript /home/kprovost/nas3/testingPopgenome_ms.R $path

date
time